### PR TITLE
Java 19: support new signature of sun.nio.ch.FileChannelImpl.map0()

### LINKED ISSUE #449: Java 19 compatibility
In Java 19 the signature of the Java_sun_nio_ch_FileChannelImpl_map0() function has changed with [JDK-8286671](https://bugs.openjdk.org/browse/JDK-8286671). This leads to the following exception when running on Java 19:
```
 Caused by: java.lang.AssertionError: java.lang.NoSuchMethodException: sun.nio.ch.FileChannelImpl.map0(int,long,long,boolean)
 	at net.openhft.chronicle.core.Jvm.getMethod0(Jvm.java:636)
 	at net.openhft.chronicle.core.Jvm.getMethod(Jvm.java:611)
 	at net.openhft.chronicle.core.OS.lambda$static$0(OS.java:55)
 	at net.openhft.chronicle.core.ClassLocal.computeValue(ClassLocal.java:54)
 	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:229)
 	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:211)
 	at java.base/java.lang.ClassValue.get(ClassValue.java:117)
 	at net.openhft.chronicle.core.OS.map0(OS.java:420)
 	at net.openhft.chronicle.core.OS.map(OS.java:388)
```

### PR DESCRIPTION
**Pull request by srt**
fixes #449

### CODE REVIEW

**Review by JerryShea — APPROVED** [review]
LGTM but would prefer @peter-lawrey review

**Comment by srt** [comment]
Anything I can to do to help getting this small improvement merged?

**Comment by JerryShea** [comment]
@srt can you please sign the [CLA](https://chronicle.software/contributor-agreement/)?

@peter-lawrey I have confirmed that this change works for Java 17 and Java 19. Please review

**Comment by srt** [comment]
@JerryShea done

**Comment by JerryShea** [comment]
Thanks @srt !

**Comment by ginkel** [comment]
Hello @JerryShea,

I'm also affected by this Java 19 incompatibility and was wondering whether you have an idea when / in which version this fix will be available (especially when using Chronicle Maps) on Maven Central.

Thanks,
Thilo

**Comment by JerryShea** [comment]
@ginkel Java 19 is not a supported JVM so use at your own risk ;)
This change is in snapshot so if you use the latest snapshot bom you will get this. See also https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Version-Support.adoc

**Pull request merged**
