### PR TITLE
Add support for hugetlbfs (custom pageSize).

### PR DESCRIPTION
**Pull request by yevgenp**
Required for Chronicle Queue hugetlbfs support

### CODE REVIEW

**Comment by tgd** [comment]
Hi Yevgen - I *think* it looks good - is the idea to introduce this new `mapAlignForPageSize` across the different call sites in bytes / wire etc? Does the `pageSize` method need any changes?

**Comment by yevgenp** [comment]
> Hi Yevgen - I _think_ it looks good - is the idea to introduce this new `mapAlignForPageSize` across the different call sites in bytes / wire etc? Does the `pageSize` method need any changes?

Yes, that's the idea. I've already done it for Bytes. I need to release this first.

**Comment by tgd** [comment]
Hi @yevgenp thanks for putting this together. I think its heading in the right direction.

**Comment by yevgenp** [comment]
@peter-lawrey I've adjusted current PR with #579. I've removed new method `mapAlignForPageSize` (though I believe the naming was better), cleaned up OS validations a bit. If you don't mind I'd prefer to keep this one.
Please rereview/approve.

**Pull request closed without merging**
